### ISSUE TITLE
Using 'envi.open' on ENVI .sli file alters endmember spectra values 

### ISSUE THREAD

**Issue by agraham9966** [spectralpython/spectralpython.github.io#2]
Hi, 

I am experiencing an issue of which I cannot conclude is an issue with a particular envi .sli file (and associated header) itself, or with something in your code using 'envi.open'. 

I have provided the following files in the attached zip folder: 
- 'cuprite-endmembers.sli' and .hdr:  46 endmembers total in file - EMs extracted from cuprite image from 2006 
- 'envi-out-EM24.sli' and .hdr : EM24, manually exported using ENVI from 'cuprite-endmembers.sli' 

The issue: 
When using 'envi.open' on 'cuprite-endmembers.sli', endmember spectral values are altered or sorted at different positions at particular spectral regions. These values are not altered or sorted however, when comparing the same endmembers opened inside of ENVI (envi reads the endmember DN values correctly and differently than envi.open in spectral python). 
An example here is 'EM24' (at row index position 12 of the cuprite-endmembers.sli endmember array). If I save that same endmember out from ENVI (which I have done for you and put in the zip file 'envi-out-EM24.sli') envi.open does not do anything to the spectral values. This can be verified by plotting: 
![SamplePlot](https://user-images.githubusercontent.com/39606276/70273148-5fcf3080-175e-11ea-8771-afe5ebd6020b.PNG)
In the above plot, EM24 in row 12 of 'cuprite-endmembers.sli' shows variations at 0.6554-0.6749 micrometers (or index 30-34. sli_file.spectra[12][30:35]) 

In summary, ENVI is able to open 'cuprite-endmembers.sli' properly without any alteration to the spectral values. But with this particular sli file, envi.open does something to the spectra, and I cannot seem to figure out the source of the issue. The only workaround is to open cuprite-endmembers.sli in envi and save the endmembers back out. Then envi.open works. But I would like to know the cause of this issue if possible. 

Much thanks and sorry if the description is confusing. I found this issue hard to explain.

[cuprite-endmembers.zip](https://github.com/spectralpython/spectralpython.github.io/files/3928818/cuprite-endmembers.zip)

**Comment by tboggs** [comment]
Hello,

I think I know what the problem is but if could, please do me two favors:

1. Provide the lines of code you used to plot the spectra.
2. Re-post your issue to the spectral project page [here](https://github.com/spectralpython/spectral/issues). This project where you currently have it posted is just the repo for the project documentation (not the actual python module).

Thanks,
Thomas

**Comment by tboggs** [comment]
Actually, don't worry about posting the code. I already know the problem. But if you can post your issue on the other repo, I'll respond there.

**Comment by agraham9966** [comment]
Hi Thomas, thanks. I don't know how I found myself here in the wrong repo! It has been reposted. Cheers, 
Alex.
